services:
  postgres:
    image: postgres
    container_name: postgres-ecom
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "ecom", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-ecom
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecom
      JWT_SECRET: getng850egvmn50gvthgwujdvt
      JWT_EXPIRATION: 100000
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres-data:
